apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: buypass-prod
spec:
  acme:
    server: https://api.buypass.com/acme/directory
    email: kisk20@live.com
    privateKeySecretRef:
      name: buypass-prod
    solvers:
    - http01:
        ingress:
          class: nginx
