apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-prod
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: kisk20@live.com
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
    - http01:
        ingress:
          class: nginx
